### ISSUE TITLE
Splunk Enterprise 9.3.x Add-On Compatibility

### ISSUE THREAD

**Issue by makal27** [splunk/Splunk-Addon-for-OCI#11]
Upon upgrading our Splunk Enterprise version to 9.3.1, we found that modular inputs associated with this TA is no longer functional.  We performed some additional troubleshooting, and was able to pinpoint the version update being the primary cause.  Curious if there is a roadmap to update the TA to have it be compatible with Splunk Enterprise 9.3.1?

Thank you!

**Comment by makal27** [comment]
[OCI_addon_error_logs.csv](https://github.com/user-attachments/files/17211105/OCI_addon_error_logs.csv)

**Comment by vrich-100** [comment]
Solution:
First, ssh into your HF and navigate to /opt/splunk/etc/system/local/server.conf, add the following to your [general] stanza:

[general]
python.version = python3.9


Second, navigate to /opt/splunk/etc/apps/TA-oci(whichever installed), mkdir local

In the local directory, vi inputs.conf and ensure the python.version is python3.7, restart your heavy forwarder.

**Comment by makal27** [comment]
Worked like a charm!

Thank you @vrich-100!
