### ISSUE TITLE
Link to latest version does not d/l latest version of the TA

### ISSUE THREAD

**Issue by ltawfall** [splunk/Splunk-Addon-for-OCI#8]
The link to d/l the addon in the directions (https://github.com/splunk/oci-arch-logging-splunk/blob/main/README/README.md#step-1-download-the-plugin) for the latest version d/l a copy of the 2.3.0 tarball

The release notes says there's a 2.3.2 version https://github.com/splunk/oci-arch-logging-splunk/blob/main/README/release-notes.md

Can you please update the latest version on 

 https://objectstorage.us-phoenix-1.oraclecloud.com/n/pcainkar/b/Public_Files/o/oci_logging_addon%2Flatest.html

**Comment by vrich-100** [comment]
Working on this.

**Comment by vrich-100** [comment]
Download link points to splunkbase now. https://splunkbase.splunk.com/app/5222
